# -*- coding: utf-8 -*-
"""sih.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsCi-fxZGhRoPPelX_7lRIDdtsoiKlSt
"""

!pip install -q ultralytics pyyaml

import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: GPU not available. Enable T4 GPU in Runtime settings.")

from google.colab import drive

drive.mount('/content/drive')

import os

DATASET_DIR = "/content/drive/MyDrive/yolo_dataset"

print("Dataset exists:", os.path.exists(DATASET_DIR))

if os.path.exists(DATASET_DIR):
    print("Contents:", os.listdir(DATASET_DIR))
else:
    print("Dataset not found. Check the folder name in Drive.")

from pathlib import Path

yaml_files = list(Path(DATASET_DIR).rglob("data.yaml"))

print("Found YAML files:")
for i, f in enumerate(yaml_files):
    print(i, f)

DATA_YAML = str(yaml_files[0])

print("Using:", DATA_YAML)

print(open(DATA_YAML).read())

import yaml
import os

# Read A1's original YAML
with open(DATA_YAML, "r") as f:
    data = yaml.safe_load(f)

# Force the correct absolute dataset path
data["path"] = DATASET_DIR

# Save corrected YAML in Colab
FIXED_YAML = "/content/data_fixed.yaml"

with open(FIXED_YAML, "w") as f:
    yaml.dump(data, f, sort_keys=False)

print(open(FIXED_YAML).read())

from glob import glob

for split in ["train", "val"]:
    image_dir = os.path.join(DATASET_DIR, "images", split)
    label_dir = os.path.join(DATASET_DIR, "labels", split)

    images = glob(os.path.join(image_dir, "*"))
    labels = glob(os.path.join(label_dir, "*.txt"))

    print(f"\n{split.upper()}")
    print("Images:", len(images))
    print("Labels:", len(labels))
    print("Image folder exists:", os.path.exists(image_dir))
    print("Label folder exists:", os.path.exists(label_dir))

from glob import glob

label_files = glob(
    os.path.join(DATASET_DIR, "labels", "train", "*.txt")
)

if label_files:
    print("Example label file:", label_files[0])
    print(open(label_files[0]).read())
else:
    print("No label files found.")

from ultralytics import YOLO

model = YOLO("yolo11n-seg.pt")

results = model.train(
    data=FIXED_YAML,
    epochs=50,
    imgsz=640,
    batch=8,
    device=0,
    project="/content/drive/MyDrive/SIH_2026/models",
    name="baseline",
    patience=10,
    workers=2,
    plots=True
)

import os
from pathlib import Path

# Check whether the expected folder exists
expected = "/content/drive/MyDrive/SIH_2026/models/baseline"

print("Expected folder exists:", os.path.exists(expected))

# Search Drive for all best.pt files
model_files = list(Path("/content/drive/MyDrive").rglob("best.pt"))

print("\nFound model files:")
for f in model_files:
    print(f)

import os

models_dir = "/content/drive/MyDrive/SIH_2026/models"

print("Models folder exists:", os.path.exists(models_dir))

if os.path.exists(models_dir):
    for root, dirs, files in os.walk(models_dir):
        level = root.replace(models_dir, "").count(os.sep)
        indent = " " * 4 * level
        print(f"{indent}{os.path.basename(root)}/")

        for file in files:
            print(f"{indent}    {file}")

from ultralytics import YOLO

# Correct path found in your output
BEST_MODEL_PATH = "/content/drive/MyDrive/SIH_2026/models/baseline-2/weights/best.pt"

best_model = YOLO(BEST_MODEL_PATH)

metrics = best_model.val(
    data=FIXED_YAML,
    imgsz=640,
    batch=8,
    device=0
)

print(metrics)

best_model.predict(
    source=os.path.join(DATASET_DIR, "images", "val"),
    conf=0.25,
    save=True,
    project="/content/drive/MyDrive/SIH_2026/models",
    name="baseline_predictions"
)

from IPython.display import Image, display
import glob

predictions = glob.glob(
    "/content/drive/MyDrive/SIH_2026/models/baseline_predictions/*"
)

print("Number of predictions:", len(predictions))

if predictions:
    display(Image(filename=predictions[0]))

import os

results_dir = "/content/drive/MyDrive/SIH_2026/models/baseline"

print("Saved files:")
for file in os.listdir(results_dir):
    print(file)

import pandas as pd

results_path = "/content/drive/MyDrive/SIH_2026/models/baseline-2/results.csv"

df = pd.read_csv(results_path)

print(df.columns.tolist())
display(df.tail())

import os
from pathlib import Path

# Search for all data.yaml files in your Drive
yaml_files = list(Path("/content/drive/MyDrive").rglob("data.yaml"))

print("Found datasets:")

for i, f in enumerate(yaml_files):
    print(i, f)

from pathlib import Path
import os

# Search your entire My Drive
yaml_files = list(Path("/content/drive/MyDrive").rglob("data.yaml"))

print("Found data.yaml files:\n")

for i, f in enumerate(yaml_files):
    print(i, f)

import os

NEW_DATASET_DIR = "/content/drive/MyDrive/content 2/yolo_dataset"
NEW_DATA_YAML = os.path.join(NEW_DATASET_DIR, "data.yaml")

print("Dataset exists:", os.path.exists(NEW_DATASET_DIR))
print("YAML exists:", os.path.exists(NEW_DATA_YAML))

print("\nNew dataset YAML:")
print(open(NEW_DATA_YAML).read())

import yaml

with open(NEW_DATA_YAML, "r") as f:
    new_data = yaml.safe_load(f)

# Set the correct absolute path
new_data["path"] = NEW_DATASET_DIR

FIXED_NEW_YAML = "/content/new_data_fixed.yaml"

with open(FIXED_NEW_YAML, "w") as f:
    yaml.dump(new_data, f, sort_keys=False)

print(open(FIXED_NEW_YAML).read())

from glob import glob

for split in ["train", "val"]:
    image_dir = os.path.join(NEW_DATASET_DIR, "images", split)
    label_dir = os.path.join(NEW_DATASET_DIR, "labels", split)

    images = glob(os.path.join(image_dir, "*"))
    labels = glob(os.path.join(label_dir, "*.txt"))

    print(f"\n{split.upper()}")
    print("Images:", len(images))
    print("Labels:", len(labels))
    print("Image folder exists:", os.path.exists(image_dir))
    print("Label folder exists:", os.path.exists(label_dir))

from ultralytics import YOLO

# Start with the same pretrained segmentation model
model_new = YOLO("yolo11n-seg.pt")

results_new = model_new.train(
    data=FIXED_NEW_YAML,
    epochs=50,
    imgsz=640,
    batch=8,
    device=0,
    project="/content/drive/MyDrive/SIH_2026/models",
    name="improved_dataset",
    patience=10,
    workers=2,
    plots=True
)

from ultralytics import YOLO

# Correct path from your Cell 20 output
BEST_MODEL_NEW = "/content/drive/MyDrive/SIH_2026/models/improved_dataset-2/weights/best.pt"

best_model_new = YOLO(BEST_MODEL_NEW)

metrics_new = best_model_new.val(
    data=FIXED_NEW_YAML,
    imgsz=640,
    batch=8,
    device=0
)

print(metrics_new)

best_model_new.predict(
    source=os.path.join(NEW_DATASET_DIR, "images", "val"),
    conf=0.25,
    save=True,
    project="/content/drive/MyDrive/SIH_2026/models",
    name="improved_predictions"
)

from IPython.display import Image, display
import glob

predictions = glob.glob(
    "/content/drive/MyDrive/SIH_2026/models/improved_predictions/*"
)

print("Number of predictions:", len(predictions))

if predictions:
    display(Image(filename=predictions[0]))

import pandas as pd

baseline_csv = "/content/drive/MyDrive/SIH_2026/models/baseline-2/results.csv"
improved_csv = "/content/drive/MyDrive/SIH_2026/models/improved_dataset-2/results.csv"

baseline_df = pd.read_csv(baseline_csv)
improved_df = pd.read_csv(improved_csv)

print("BASELINE — last epoch")
display(baseline_df.tail(1))

print("IMPROVED — last epoch")
display(improved_df.tail(1))

import pandas as pd

baseline_csv = "/content/drive/MyDrive/SIH_2026/models/baseline-2/results.csv"
improved_csv = "/content/drive/MyDrive/SIH_2026/models/improved_dataset-2/results.csv"

baseline_df = pd.read_csv(baseline_csv)
improved_df = pd.read_csv(improved_csv)

# Find the best epoch using Mask mAP50
baseline_best = baseline_df.loc[baseline_df["metrics/mAP50(M)"].idxmax()]
improved_best = improved_df.loc[improved_df["metrics/mAP50(M)"].idxmax()]

comparison = pd.DataFrame({
    "Metric": [
        "Mask Precision",
        "Mask Recall",
        "Mask mAP50",
        "Mask mAP50-95"
    ],
    "Baseline": [
        baseline_best["metrics/precision(M)"],
        baseline_best["metrics/recall(M)"],
        baseline_best["metrics/mAP50(M)"],
        baseline_best["metrics/mAP50-95(M)"]
    ],
    "Improved": [
        improved_best["metrics/precision(M)"],
        improved_best["metrics/recall(M)"],
        improved_best["metrics/mAP50(M)"],
        improved_best["metrics/mAP50-95(M)"]
    ]
})

comparison["Change"] = comparison["Improved"] - comparison["Baseline"]

display(comparison)

